/*
 * generated by Xtext 2.12.0
 */
package org.slizaa.neo4j.opencypher.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.XtextRunner
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith
import org.slizaa.neo4j.opencypher.openCypher.Cypher

@RunWith(XtextRunner)
@InjectWith(OpenCypherInjectorProvider)
class OpenCypherParsingTest {
	@Inject
	ParseHelper<Cypher> parseHelper
	
	@Test
	def void loadModel() {
		val result = parseHelper.parse('''
			MATCH (n) return true;
		''')
		Assert.assertNotNull(result)
		Assert.assertTrue(result.eResource.errors.isEmpty)
	}
}
